### ISSUE TITLE
Extra space at the bottom

### ISSUE THREAD

**Issue by tvxqljw** [shahxadakram/flutter_tex#10]
When I changed some code  in this demo,  I found  extra space at the bottom; 

main.dart core code:
```flutter
 return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: Text("Flutter TeX Example"),
          actions: <Widget>[
            IconButton(
                icon: Icon(Icons.refresh),
                onPressed: () {
                  setState(() {});
                })
          ],
        ),
        body: Column(
          children: <Widget>[
            TeXView(
              // any random unique index (0-9) is mandatory if you are using multiple TeXView in a List view on same page.
              index: 0,
              teXHTML: teXHTML,
              onRenderFinished: (height) {
                print("Height is : $height");
              },
              onPageFinished: (string) {
                print("Page Loading finished");
              },
            ),
            Container(color: Colors.pink, height: 10.0, width: double.infinity,)
          ],
        ),
      ),
    );
```

teXHTML.dart
```flutter
String teXHTML = r"""
     
     <style>
       .card {
         box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
         transition: 0.3s;
         width: 200;
         font-size:4.2vw;
          color:red;
          background-color:yellow;
       }
     </style>

    <div class="card">1</div>
   """;
```

And it comes to this :
![image](https://user-images.githubusercontent.com/7098129/60935597-fe18b080-a2fc-11e9-9819-51d6dde2e699.png)

Also I found that there was another space appear when I added a new line ;
```flutter
String teXHTML = r"""
     
     <style>
       .card {
         box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
         transition: 0.3s;
         width: 200;
         font-size:4.2vw;
          color:red;
          background-color:yellow;
       }
     </style>

    <div class="card">1</div>
    <div class="card">2</div>
   """;
```

![image](https://user-images.githubusercontent.com/7098129/60935765-931ba980-a2fd-11e9-959d-ac1323d5b356.png)

How can i hide this space? 

---------------------
config:
```flutter
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  json_annotation: ^2.0.0
  toast: ^0.1.3
  dio: ^2.1.0
  flutter_tex: ^1.0.3
  flutter:
    sdk: flutter
```

**Comment by shahxadakram** [comment]
This issue has been resolved, Please upgrade to latest version   flutter_tex: ^1.0.7 ,  and be careful there are some minor changes in new version please correct them before proceed..

**Comment by tvxqljw** [comment]
Thank you so much for your update and reply！
However, I got a new problem during running , after I updated version from ^1.0.3 to ^1.0.7
![image](https://user-images.githubusercontent.com/7098129/61193741-e2901a00-a6ef-11e9-88c6-3a9ee70fb5ee.png)

It came out a error when I run `pod install`
![image](https://user-images.githubusercontent.com/7098129/61193943-f5efb500-a6f0-11e9-95c9-dee93cbe2aaa.png)

There are only webview_flutter.podspec file in the directory
![image](https://user-images.githubusercontent.com/7098129/61193976-4109c800-a6f1-11e9-9193-82ddf18c74ff.png)

Also I find there are some changes in `.ios/Flutter/.symlinks/` directory between version ^1.0.3 & ^1.0.7
( image below is  from version ^1.0.3 )
![image](https://user-images.githubusercontent.com/7098129/61194023-84fccd00-a6f1-11e9-9465-1a32548bf214.png)

I can't verify your new change because I can't run my flutter app after upgrade.
