### ISSUE TITLE
ERR_CLEARTEXT_NOT_PERMITTED

### ISSUE THREAD

**Issue by RafaelOO** [shahxadakram/flutter_tex#5]
When trying to compile the example, I got a "page not found error because net:: ERR_CLEARTEXT_NOT_PERMITTED"
 I am using latest version of flutter to the date of writing this text on a android 9 device.

**Comment by OscarEReyes** [comment]
Did you manage to fix it?

**Comment by RafaelOO** [comment]
Yes,  I did.
