### ISSUE TITLE
Unicode Converted

### ISSUE THREAD

**Issue by maheshbhattaraai** [shahxadakram/flutter_tex#8]
Chnages into unicode

**Comment by farazahmad759** [comment]
@maheshbhattaraai, I don't know whether you are suffering from the same issue as I am or not, so I'm adding a few details.

The text I want to show in TexView contains HTML codes like &#39; (equivalent to apostrophe). Example text:
----------------------------
You&#39;re awesome.
----------------------------
Ideally it should show up "You're awesome." but what it shows up in the flutter app is You& (without angle brackets), and the text after & sign is clipped.

**Comment by maheshbhattaraai** [comment]
Your example code is also conerted into unicode. Can you create new example repo . Flutter version is 1.6.

**Comment by shahxadakram** [comment]
No need to use any unicode just write as normal but make sure you are using a raw string.

```
String teXHTML = r"""
     You're awesome.
   """;
```
here **r** is mandatory before starting string quotes..

**Comment by maheshbhattaraai** [comment]
I am not using unicode . But the result is showing unicode for mathematical equation.
