### ISSUE TITLE
Can a TexView be refreshed / re-rendered?

### ISSUE THREAD

**Issue by OscarEReyes** [shahxadakram/flutter_tex#9]
I attempted to place a TexView inside a StreamBuilder that passes some text to be displayed.
The TexView stays unchanged.

Is there a correct way to re-render it?

**Comment by shahxadakram** [comment]
Sorry currently there is nothing like that, but it would be soon..

**Comment by takdw** [comment]
I am having this issue as well. It would be really cool if we could re-render the `TeXView` when the input data (`teXHTML`) changes.

**Comment by takdw** [comment]
So I have tried wrapping the `TeXView` in `StatefulWidget` and also a `Consumer` widget but I can't force the `TeXView` to be rebuilt. Is there any way I can achieve this?

**Comment by OscarEReyes** [comment]
@takdw 
So I managed to get something working, still not sure if it is an efficient solution.

My need was to have the TexView change as the user types text (or presses buttons like a calculator, still working on the input) and have the TexView change to show the appropriate TeX rendered.

Look up the WebView documentation and look into the WebViewController and its loadUrl Method.
I used the BLoC pattern to handle this documentation. 

Although I think I ended up using a pure WebViewController and borrowing code from the TexView. When you create a WebView you can get the controller for it. I would have to look into the documentation. Let me know if this helps you get started.

**Comment by shahxadakram** [comment]
loadUrl method wont work as that don't support  laod from assets, if you want this you have to go to prior version before removing the server. as server makes it to load very slow, so I removed that and customized it to load directly from assets without server..

**Comment by shahxadakram** [comment]
Now this you can rerender or refresh the TeXView on setState, Please install latest version

`flutter_tex: ^1.0.8`.
